### ISSUE TITLE
Ajax格式有所变化

### ISSUE THREAD

**Issue by OrangeShen** [Python3WebSpider/Jiepai#2]
2018-04-01 抓取数据时发现image_detail已经改成了image_list，需要修改get_iamges函数

**Comment by Germey** [comment]
方便提交一个PR吗

**Comment by OrangeShen** [comment]
提交了，第一次PR，有什么不足的地方还请多多包涵，代码在我电脑上实测抓取成功的




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：897139816@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年04月02日 15:29，Germey 写道： 方便提交一个PR吗

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Python3WebSpider/Jiepai","title":"Python3WebSpider/Jiepai","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Python3WebSpider/Jiepai"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Germey in #2: 方便提交一个PR吗"}],"action":{"name":"View Issue","url":"https://github.com/Python3WebSpider/Jiepai/issues/2#issuecomment-377874545"}}}

**Comment by wsc30curry** [comment]
@OrangeShen 
我把params参数from：改成search_tab就会爬到一半出现：
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\PYTHON\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\PYTHON\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\web crawler\AJAX_use_NBAtoutiao.py", line 63, in main
    for item in get_images(json):
  File "D:\web crawler\AJAX_use_NBAtoutiao.py", line 38, in get_images
    for image in image_list:
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/web crawler/AJAX_use_NBAtoutiao.py", line 71, in <module>
    pool.map(main, groups)
  File "D:\PYTHON\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\PYTHON\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
TypeError: 'NoneType' object is not iterable

**Comment by pythonkerry** [comment]
@WSCZou 判断一下image_list是否为空：
            if image_list:
                for image in image_list:
                    yield {
                        'image': image.get('url'),
                        'title': title
                    }

**Comment by vvyx** [comment]
楼上是对的，对images增加一个是否为None的判断 一些image_list是空的

**Comment by Germey** [comment]
thanks~ updated~
